/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/bulk/compensation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Bulk Update Compensation */
        put: operations["bulk_update_compensation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee"];
        /** Update Employee */
        put: operations["update_employee"];
        post?: never;
        /** Delete Employee */
        delete: operations["delete_employee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Employee */
        post: operations["approve_employee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Employee */
        post: operations["reject_employee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles"];
        put?: never;
        /** Create Vehicle */
        post: operations["create_vehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vehicle */
        get: operations["get_vehicle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Vehicle */
        patch: operations["update_vehicle"];
        trace?: never;
    };
    "/api/v1/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions"];
        put?: never;
        /** Create Session */
        post: operations["create_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/active/by-date/{session_date}/{shift}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Session */
        get: operations["get_active_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Session */
        post: operations["finalize_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock Session */
        post: operations["unlock_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/sessions/{session_id}/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee Attendance */
        get: operations["get_employee_attendance"];
        /** Record Attendance */
        put: operations["record_attendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Attendance */
        get: operations["get_session_attendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/sessions/{session_id}/vehicles/{vehicle_id}/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Vehicle */
        post: operations["assign_vehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/sessions/{session_id}/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee Assignment */
        get: operations["get_employee_assignment"];
        put?: never;
        post?: never;
        /** Unassign Vehicle */
        delete: operations["unassign_vehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/sessions/{session_id}/vehicles/{vehicle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vehicle Assignments */
        get: operations["get_vehicle_assignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pay/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pay Rates */
        get: operations["get_pay_rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pay/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Pay */
        post: operations["calculate_pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pay/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pay Summary */
        get: operations["get_pay_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Trip Status */
        put: operations["update_trip_status"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendanceRecordResponse */
        AttendanceRecordResponse: {
            /** Sessionid */
            sessionId: string;
            /** Employeeid */
            employeeId: string;
            /** Status */
            status: string;
            /** Arrivaltime */
            arrivalTime?: string | null;
            /** Recordedby */
            recordedBy: string;
            /** Remarks */
            remarks?: string | null;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Hoursworked
             * @default 8
             */
            hoursWorked: number;
            /**
             * Extrahours
             * @default 0
             */
            extraHours: number;
            /**
             * Basepay
             * @default 0
             */
            basePay: number | null;
            /**
             * Extradutypay
             * @default 0
             */
            extraDutyPay: number | null;
            /**
             * Totalpay
             * @default 0
             */
            totalPay: number | null;
            /** Id */
            _id?: string | null;
            /**
             * Recordedat
             * Format: date-time
             */
            recordedAt?: string;
        };
        /** AttendanceRecordUpdate */
        AttendanceRecordUpdate: {
            /** Status */
            status?: string | null;
            /** Arrivaltime */
            arrivalTime?: string | null;
            /** Remarks */
            remarks?: string | null;
            /** Version */
            version?: number | null;
            /** Hoursworked */
            hoursWorked?: number | null;
            /** Extrahours */
            extraHours?: number | null;
            /** Basepay */
            basePay?: number | null;
            /** Extradutypay */
            extraDutyPay?: number | null;
            /** Totalpay */
            totalPay?: number | null;
        };
        /** AttendanceSessionCreate */
        AttendanceSessionCreate: {
            /** Sessiondate */
            sessionDate: string;
            /** Shift */
            shift: string;
            /**
             * Status
             * @default in_progress
             */
            status: string;
            /** Supervisorid */
            supervisorId: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Sessionid */
            sessionId?: string | null;
        };
        /** AttendanceSessionResponse */
        AttendanceSessionResponse: {
            /** Sessiondate */
            sessionDate: string;
            /** Shift */
            shift: string;
            /**
             * Status
             * @default in_progress
             */
            status: string;
            /** Supervisorid */
            supervisorId: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Id */
            _id?: string | null;
            /** Finalizedat */
            finalizedAt?: string | null;
            /** Finalizedby */
            finalizedBy?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** BulkCompensationItem */
        BulkCompensationItem: {
            /** Employeeid */
            employeeId: string;
            /** Baserate */
            baseRate?: number | null;
            /** Extrahours */
            extraHours?: number | null;
            /** Incentive */
            incentive?: number | null;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Employeeid */
            employeeId: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Photopath */
            photoPath?: string | null;
            /** Displayorder */
            displayOrder?: number | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Phone */
            phone?: string | null;
            /** Contractor */
            contractor?: string | null;
            /** Remarks */
            remarks?: string | null;
            /** Requestedby */
            requestedBy?: string | null;
            /** Approvedby */
            approvedBy?: string | null;
            /** Baserate */
            baseRate?: number | null;
            /**
             * Extrahours
             * @default 0
             */
            extraHours: number | null;
            /**
             * Incentive
             * @default 0
             */
            incentive: number | null;
        };
        /** EmployeeResponse */
        EmployeeResponse: {
            /** Employeeid */
            employeeId: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Photopath */
            photoPath?: string | null;
            /** Displayorder */
            displayOrder?: number | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Phone */
            phone?: string | null;
            /** Contractor */
            contractor?: string | null;
            /** Remarks */
            remarks?: string | null;
            /** Requestedby */
            requestedBy?: string | null;
            /** Approvedby */
            approvedBy?: string | null;
            /** Baserate */
            baseRate?: number | null;
            /**
             * Extrahours
             * @default 0
             */
            extraHours: number | null;
            /**
             * Incentive
             * @default 0
             */
            incentive: number | null;
            /** Id */
            _id?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
        };
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Photopath */
            photoPath?: string | null;
            /** Displayorder */
            displayOrder?: number | null;
            /** Status */
            status?: string | null;
            /** Phone */
            phone?: string | null;
            /** Contractor */
            contractor?: string | null;
            /** Remarks */
            remarks?: string | null;
            /** Baserate */
            baseRate?: number | null;
            /** Extrahours */
            extraHours?: number | null;
            /** Incentive */
            incentive?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PayCalculationRequest */
        PayCalculationRequest: {
            /** Category */
            category: string;
            /** Status */
            status: string;
            /**
             * Hoursworked
             * @default 8
             */
            hoursWorked: number;
            /**
             * Extrahours
             * @default 0
             */
            extraHours: number;
        };
        /** PayCalculationResponse */
        PayCalculationResponse: {
            /** Category */
            category: string;
            /** Status */
            status: string;
            /** Baserate */
            baseRate: number;
            /** Hourlyrate */
            hourlyRate: number;
            /** Hoursworked */
            hoursWorked: number;
            /** Extrahours */
            extraHours: number;
            /** Basepay */
            basePay: number;
            /** Extradutypay */
            extraDutyPay: number;
            /** Totalpay */
            totalPay: number;
        };
        /** TripTimelineEvent */
        TripTimelineEvent: {
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Recordedby */
            recordedBy: string;
            /** Locationname */
            locationName?: string | null;
            /** Receivername */
            receiverName?: string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleAssignmentResponse */
        VehicleAssignmentResponse: {
            /** Sessionid */
            sessionId: string;
            /** Employeeid */
            employeeId: string;
            /** Vehicleid */
            vehicleId: string;
            /**
             * Assignedat
             * Format: date-time
             */
            assignedAt?: string;
            /** Assignedby */
            assignedBy: string;
            /** Unassignedat */
            unassignedAt?: string | null;
            /** Unassignedby */
            unassignedBy?: string | null;
            /** Id */
            _id?: string | null;
        };
        /** VehicleCreate */
        VehicleCreate: {
            /** Vehiclenumber */
            vehicleNumber: string;
            /** Vehicletype */
            vehicleType: string;
            /** Name */
            name?: string | null;
            /**
             * Capacity
             * @default 8
             */
            capacity: number;
            /**
             * Status
             * @default available
             */
            status: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** VehicleResponse */
        VehicleResponse: {
            /** Vehiclenumber */
            vehicleNumber: string;
            /** Vehicletype */
            vehicleType: string;
            /** Name */
            name?: string | null;
            /**
             * Capacity
             * @default 8
             */
            capacity: number;
            /**
             * Status
             * @default available
             */
            status: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            _id?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
        };
        /** VehicleTripCreate */
        VehicleTripCreate: {
            /** Sessionid */
            sessionId: string;
            /** Vehicleid */
            vehicleId: string;
            /** Vehiclenumber */
            vehicleNumber: string;
            /** Driveremployeeid */
            driverEmployeeId?: string | null;
            /** Drivername */
            driverName?: string | null;
            /** Destinationlocation */
            destinationLocation: string;
            /**
             * Productdetails
             * @default Material / Aggregate Delivery
             */
            productDetails: string | null;
            /**
             * Status
             * @default dispatched
             */
            status: string;
            /** Remarks */
            remarks?: string | null;
        };
        /** VehicleTripResponse */
        VehicleTripResponse: {
            /** Sessionid */
            sessionId: string;
            /** Vehicleid */
            vehicleId: string;
            /** Vehiclenumber */
            vehicleNumber: string;
            /** Driveremployeeid */
            driverEmployeeId?: string | null;
            /** Drivername */
            driverName?: string | null;
            /** Destinationlocation */
            destinationLocation: string;
            /**
             * Productdetails
             * @default Material / Aggregate Delivery
             */
            productDetails: string | null;
            /**
             * Status
             * @default dispatched
             */
            status: string;
            /** Remarks */
            remarks?: string | null;
            /** Id */
            _id?: string | null;
            /**
             * Dispatchedat
             * Format: date-time
             */
            dispatchedAt?: string;
            /** Dispatchedby */
            dispatchedBy: string;
            /** Reachedlocationat */
            reachedLocationAt?: string | null;
            /** Deliveredat */
            deliveredAt?: string | null;
            /** Returnedat */
            returnedAt?: string | null;
            /** Receivername */
            receiverName?: string | null;
            /** Timeline */
            timeline?: components["schemas"]["TripTimelineEvent"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt?: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
        };
        /** VehicleTripUpdateStatus */
        VehicleTripUpdateStatus: {
            /** Status */
            status: string;
            /** Locationname */
            locationName?: string | null;
            /** Receivername */
            receiverName?: string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /** VehicleUpdate */
        VehicleUpdate: {
            /** Vehiclenumber */
            vehicleNumber?: string | null;
            /** Vehicletype */
            vehicleType?: string | null;
            /** Name */
            name?: string | null;
            /** Capacity */
            capacity?: number | null;
            /** Status */
            status?: string | null;
            /** Active */
            active?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_employees: {
        parameters: {
            query?: {
                category?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_compensation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCompensationItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_employee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_employee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles: {
        parameters: {
            query?: {
                vehicle_type?: string | null;
                status?: string | null;
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: {
                session_date?: string | null;
                shift?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_date: string;
                shift: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_attendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_attendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_attendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecordResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_vehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vehicle_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_assignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unassign_vehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle_assignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAssignmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pay_rates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    calculate_pay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayCalculationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayCalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pay_summary: {
        parameters: {
            query?: {
                session_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips: {
        parameters: {
            query?: {
                session_id?: string | null;
                vehicle_id?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTripResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleTripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleTripUpdateStatus"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
